import { User, Conversation } from "@/types/chat";

export const currentUser: User = {
  id: "me",
  name: "You",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=me",
  status: "online",
};

export const users: User[] = [
  {
    id: "u1",
    name: "Alice Johnson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice",
    status: "online",
  },
  {
    id: "u2",
    name: "Bob Smith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bob",
    status: "away",
    lastSeen: "5 minutes ago",
  },
  {
    id: "u3",
    name: "Carol White",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=carol",
    status: "offline",
    lastSeen: "2 hours ago",
  },
  {
    id: "u4",
    name: "David Lee",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=david",
    status: "online",
  },
  {
    id: "u5",
    name: "Emma Davis",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma",
    status: "online",
  },
];

export const initialConversations: Conversation[] = [
  {
    id: "c1",
    participants: [currentUser, users[0]],
    isGroup: false,
    unreadCount: 2,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    messages: [
      {
        id: "m1",
        content: "Hey! How are you doing?",
        senderId: "u1",
        timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m2",
        content: "I'm doing great! Just working on a new project 🚀",
        senderId: "me",
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m3",
        content: "That sounds exciting! What kind of project?",
        senderId: "u1",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m4",
        content: "A full-stack chat application with Next.js 😄",
        senderId: "u1",
        timestamp: new Date(Date.now() - 1800000).toISOString(),
        type: "text",
        status: "delivered",
      },
      {
        id: "m5",
        content: "Can't wait to see it!",
        senderId: "u1",
        timestamp: new Date(Date.now() - 900000).toISOString(),
        type: "text",
        status: "delivered",
      },
    ],
    lastMessage: {
      id: "m5",
      content: "Can't wait to see it!",
      senderId: "u1",
      timestamp: new Date(Date.now() - 900000).toISOString(),
      type: "text",
      status: "delivered",
    },
  },
  {
    id: "c2",
    participants: [currentUser, users[1]],
    isGroup: false,
    unreadCount: 0,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    messages: [
      {
        id: "m6",
        content: "Did you review the pull request I sent?",
        senderId: "me",
        timestamp: new Date(Date.now() - 7200000).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m7",
        content: "Yes! Left some comments. Overall looks good though 👍",
        senderId: "u2",
        timestamp: new Date(Date.now() - 5400000).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m8",
        content: "Perfect, I'll address the comments today",
        senderId: "me",
        timestamp: new Date(Date.now() - 5000000).toISOString(),
        type: "text",
        status: "read",
      },
    ],
    lastMessage: {
      id: "m8",
      content: "Perfect, I'll address the comments today",
      senderId: "me",
      timestamp: new Date(Date.now() - 5000000).toISOString(),
      type: "text",
      status: "read",
    },
  },
  {
    id: "c3",
    participants: [currentUser, users[2], users[3], users[4]],
    isGroup: true,
    groupName: "Dev Team 🛠️",
    groupAvatar: "https://api.dicebear.com/7.x/identicon/svg?seed=devteam",
    unreadCount: 5,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    messages: [
      {
        id: "m9",
        content: "Team standup in 10 minutes!",
        senderId: "u3",
        timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m10",
        content: "On my way 🏃",
        senderId: "u4",
        timestamp: new Date(Date.now() - 3600000 * 4.5).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m11",
        content: "Deployment went successfully! 🎉",
        senderId: "u5",
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        type: "text",
        status: "delivered",
      },
      {
        id: "m12",
        content: "Great work everyone! The new features are live.",
        senderId: "u3",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        type: "text",
        status: "delivered",
      },
      {
        id: "m13",
        content: "Congrats team! 🥳",
        senderId: "u4",
        timestamp: new Date(Date.now() - 1200000).toISOString(),
        type: "text",
        status: "delivered",
      },
    ],
    lastMessage: {
      id: "m13",
      content: "Congrats team! 🥳",
      senderId: "u4",
      timestamp: new Date(Date.now() - 1200000).toISOString(),
      type: "text",
      status: "delivered",
    },
  },
  {
    id: "c4",
    participants: [currentUser, users[3]],
    isGroup: false,
    unreadCount: 0,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    messages: [
      {
        id: "m14",
        content: "Hey, are you free for a quick call?",
        senderId: "u4",
        timestamp: new Date(Date.now() - 86400000).toISOString(),
        type: "text",
        status: "read",
      },
      {
        id: "m15",
        content: "Sure, give me 5 minutes",
        senderId: "me",
        timestamp: new Date(Date.now() - 86000000).toISOString(),
        type: "text",
        status: "read",
      },
    ],
    lastMessage: {
      id: "m15",
      content: "Sure, give me 5 minutes",
      senderId: "me",
      timestamp: new Date(Date.now() - 86000000).toISOString(),
      type: "text",
      status: "read",
    },
  },
  {
    id: "c5",
    participants: [currentUser, users[4]],
    isGroup: false,
    unreadCount: 1,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    messages: [
      {
        id: "m16",
        content: "Check out this article on React Server Components!",
        senderId: "u5",
        timestamp: new Date(Date.now() - 43200000).toISOString(),
        type: "text",
        status: "delivered",
      },
    ],
    lastMessage: {
      id: "m16",
      content: "Check out this article on React Server Components!",
      senderId: "u5",
      timestamp: new Date(Date.now() - 43200000).toISOString(),
      type: "text",
      status: "delivered",
    },
  },
];
